In [ ]:
#Description : This progrm detects if an email is spam (1) or not (0)

In [ ]:
#Import libraries
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [ ]:
#Load the data and print the first 5 rows.

In [ ]:
#Load the data
from google.colab import files
uploaded = files.upload()

Saving spamham.csv to spamham.csv


In [ ]:
df = pd.read_csv('spamham.csv')
df.head(5)

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
#Print the shape (Get the number of rows nd columns)
df.shape

(5728, 2)

In [ ]:
#Get the columns names
df.columns

Index(['text', 'spam'], dtype='object')

In [ ]:
#check for duplicates and remove them
df.drop_duplicates(inplace = True)

In [ ]:
#Show the new shape(number of rows and columns)
df.shape

(5695, 2)

In [ ]:
# show the number of missing (NAN , NAN , na) data for each column
df.isnull().sum()

text    0
spam    0
dtype: int64

In [ ]:
#Download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def process_text(text):

  #1 remove punctuation
  #2 remove stopwords
  #3 return a list of clean text words

  #1
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)

  #2
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #3
  return clean_words

In [ ]:
#show the tokenization ( a list of tokens also called lemmas)
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, corporate, ...
1    [Subject, stock, trading, gunslinger, fanny, m...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, money, get, software, cds, software,...
Name: text, dtype: object

In [ ]:
# Example 
message4 = 'hello world hello hello world play'
message5 = 'test test test test one hello'
print(message4)
print()

# convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4], [message5]] )
print(bow4)

hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1


In [ ]:
print()
print(bow4.shape)


(2, 5)


In [ ]:
# Convert a collection of text to a  matriz of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [ ]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size=0.20, random_state = 0)

In [ ]:
#Get the shape of messages_bow
messages_bow.shape

(5695, 37229)

In [ ]:
#Create and train the Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train, y_train)

In [ ]:
#Print the Predictions
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [ ]:
#Print the actual values
print(y_train)
print(y_train.values)

3337    0
2104    0
3905    0
461     1
314     1
       ..
4950    0
3273    0
1653    0
2611    0
2736    0
Name: spam, Length: 4556, dtype: int64
[0 0 0 ... 0 0 0]


In [ ]:
#Evaluate the model on the training data set 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_train)
print(classification_report(y_train, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556



In [ ]:
print()
print('confusion Matrix: \n', confusion_matrix(y_train, pred))


confusion Matrix: 
 [[3445   12]
 [   1 1098]]


In [ ]:
print('Accuracy: ', accuracy_score(y_train, pred))

Accuracy:  0.9971466198419666


In [ ]:
print(classifier.predict(x_test))

#print the actual values
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [ ]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(x_test)
print(classification_report(y_test, pred))
print()
print('confusion Marix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: ', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


confusion Marix: 
 [[862   8]
 [  1 268]]

Accuracy:  0.9920983318700615
